import {DurableObject} from 'cloudflare:workers';
import {WORLD,json,clamp,clean,day,MAX_EVENTS} from './util.js';
import {bootstrap,move,strategies,projects,spies,daily,publicState} from './sim.js';
import {ensureConversations,localLine,deepLine,remember} from './brain.js';
const TICK=5000;
export default{async fetch(req,env){const u=new URL(req.url),allow=env.ALLOWED_ORIGIN||'*',origin=req.headers.get('Origin')||'',cors={'access-control-allow-origin':allow==='*'?'*':allow,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(u.pathname==='/health')return new Response(JSON.stringify({ok:true,service:'bellweather-world',world:env.WORLD_NAME||WORLD}),{headers:{...cors,'content-type':'application/json'}});if(allow!=='*'&&origin&&origin!==allow)return new Response('Origin not allowed',{status:403,headers:cors});const stub=env.WORLD.getByName(env.WORLD_NAME||WORLD),target=new URL(req.url);target.hostname='world.internal';const res=await stub.fetch(new Request(target,req)),h=new Headers(res.headers);for(const[k,v]of Object.entries(cors))h.set(k,v);return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h,webSocket:res.webSocket})}};
export class BellweatherWorld extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.state=null;this.keyCursor=0;ctx.blockConcurrencyWhile(async()=>{ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,ts INTEGER,world_day INTEGER,kind TEXT,text TEXT,payload TEXT);CREATE INDEX IF NOT EXISTS ev_ts ON events(ts DESC);CREATE TABLE IF NOT EXISTS memories(id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id INTEGER,ts INTEGER,summary TEXT);CREATE INDEX IF NOT EXISTS mem_a ON memories(agent_id,ts DESC);`);this.state=await ctx.storage.get('world_state')||null;ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'));if(this.state?.initialized)await this.schedule()})}
  admin(req){return!!this.env.ADMIN_TOKEN&&(req.headers.get('authorization')||'')===`Bearer ${this.env.ADMIN_TOKEN}`}
  async fetch(req){const u=new URL(req.url);if(u.pathname==='/ws'){if((req.headers.get('Upgrade')||'').toLowerCase()!=='websocket')return new Response('WebSocket required',{status:426});const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({id:crypto.randomUUID(),joined:Date.now()});server.send(JSON.stringify({type:'hello',initialized:!!this.state?.initialized,viewers:this.ctx.getWebSockets().length,serverNow:Date.now()}));server.send(JSON.stringify(this.state?.initialized?{type:'snapshot',state:this.public(true)}:{type:'bootstrap_required'}));return new Response(null,{status:101,webSocket:client})}if(u.pathname==='/snapshot')return this.state?.initialized?json({initialized:true,state:this.public(true)}):json({initialized:false},503);if(u.pathname==='/events'){const n=clamp(u.searchParams.get('limit')||100,1,500),rows=this.ctx.storage.sql.exec('SELECT id,ts,world_day,kind,text,payload FROM events ORDER BY id DESC LIMIT ?',n).toArray();return json({events:rows.map(r=>({...r,payload:r.payload?JSON.parse(r.payload):null}))})}if(u.pathname==='/admin/time'&&req.method==='POST'){if(!this.admin(req))return json({error:'unauthorized'},401);if(!this.state?.initialized)return json({error:'not initialized'},409);const b=await req.json().catch(()=>({})),m=[1,5,20,100].includes(+b.multiplier)?+b.multiplier:1;this.state.timeMultiplier=m;this.event('world',`World speed changed to ${m}×.`,{multiplier:m});await this.save();this.push({type:'state',state:this.public(false)});return json({ok:true,multiplier:m})}if(u.pathname==='/admin/reset'&&req.method==='POST'){if(!this.admin(req))return json({error:'unauthorized'},401);await this.ctx.storage.delete('world_state');this.ctx.storage.sql.exec('DELETE FROM events;DELETE FROM memories;');this.state=null;this.push({type:'reset'});return json({ok:true})}return json({ok:true,initialized:!!this.state?.initialized,viewers:this.ctx.getWebSockets().length})}
  async webSocketMessage(ws,msg){let d;try{d=JSON.parse(typeof msg==='string'?msg:new TextDecoder().decode(msg))}catch{return}if(d.type==='bootstrap'&&!this.state?.initialized){if(!this.env.ADMIN_TOKEN||d.adminToken!==this.env.ADMIN_TOKEN){ws.send(JSON.stringify({type:'bootstrap_denied'}));return}this.state=bootstrap(d.state||{});await this.save();this.event('world',`The shared world came online with ${this.state.agents.length} residents.`);await this.schedule();this.push({type:'snapshot',state:this.public(true)});return}if(d.type==='request_snapshot'&&this.state?.initialized)ws.send(JSON.stringify({type:'snapshot',state:this.public(true)}));if(d.type==='viewer'){const a=ws.deserializeAttachment()||{};ws.serializeAttachment({...a,camera:clean(d.camera,40),focus:clean(d.focus,80),lastSeen:Date.now()})}}
  async alarm(){if(!this.state?.initialized)return;const now=Date.now(),elapsed=Math.max(0,Math.min(900000,now-(this.state.lastStepMs||now)))/1000,old=day(this.state),worldSec=elapsed*20*(this.state.timeMultiplier||1);this.state.lastStepMs=now;this.state.worldTimeSec+=worldSec;this.state.revision++;const ev=(k,t,p)=>this.event(k,t,p);move(this.state,worldSec);projects(this.state,elapsed,ev);strategies(this.state,ev);spies(this.state,worldSec,ev);ensureConversations(this.state);await this.progressConversations();for(let d=old+1;d<=day(this.state);d++)daily(this.state,d,ev);await this.save();this.push({type:'state',state:this.public(false)});await this.schedule()}
  async progressConversations(){let calls=0;for(const c of this.state.conversations){if(c.status!=='active'||Date.now()<c.nextTurnAt)continue;const a=this.state.agents.find(x=>x.id===(c.turn%2?c.bId:c.aId)),b=this.state.agents.find(x=>x.id===(c.turn%2?c.aId:c.bId));if(!a||!b){c.status='ended';c.endedAt=Date.now();continue}let line;if(c.mode==='deep'&&calls<1&&[this.env.DEEPSEEK_API_KEY_1,this.env.DEEPSEEK_API_KEY_2,this.env.DEEPSEEK_API_KEY_3].some(Boolean)){calls++;try{line=await deepLine(this.env,this.keyCursor++,this.state,a,b,c);this.state.stats.deepTurns++}catch{line=localLine(this.state,a,b,c);this.state.stats.localTurns++}}else{line=localLine(this.state,a,b,c);this.state.stats.localTurns++}c.lines.push({speakerId:a.id,speaker:a.name,text:line,at:Date.now()});c.lines=c.lines.slice(-18);c.turn++;c.nextTurnAt=Date.now()+5000+Math.floor(Math.random()*7000);const mem=remember(this.state,a,b,c,line);this.ctx.storage.sql.exec('INSERT INTO memories(agent_id,ts,summary) VALUES(?,?,?)',a.id,Date.now(),clean(mem,220));this.event('conversation',`${a.name}: ${line}`,{conversationId:c.id,speakerId:a.id,listenerId:b.id,mode:c.mode,topic:c.topic});if(c.turn>=c.maxTurns){c.status='ended';c.endedAt=Date.now()}}}
  schedule(){return this.ctx.storage.setAlarm(Date.now()+TICK)}
  event(kind,text,payload=null){if(!this.state)return;const e={id:`${Date.now()}-${this.state.revision}-${Math.floor(Math.random()*9999)}`,ts:Date.now(),day:day(this.state),kind,text:clean(text,500),payload};this.state.recentEvents.push(e);this.state.recentEvents=this.state.recentEvents.slice(-MAX_EVENTS);this.ctx.storage.sql.exec('INSERT INTO events(ts,world_day,kind,text,payload) VALUES(?,?,?,?,?)',e.ts,e.day,e.kind,e.text,payload?JSON.stringify(payload):null);this.push({type:'event',event:e})}
  save(){return this.state?this.ctx.storage.put('world_state',this.state):Promise.resolve()}
  public(full=false){return publicState(this.state,this.ctx.getWebSockets().length,full)}
  push(m){const raw=JSON.stringify(m);for(const ws of this.ctx.getWebSockets())try{ws.send(raw)}catch{}}
}
